## Server Configuration
SERVER_NAME: "go-whatsapp-rest"
SERVER_IP: "0.0.0.0"
SERVER_PORT: "3000"
SERVER_STORE_PATH: "./config/stores"
SERVER_UPLOAD_PATH: "./config/uploads"
SERVER_UPLOAD_LIMIT: 8
SERVER_LOG_LEVEL: "info"

## Router Configuration
ROUTER_BASE_PATH: "/api/v1/whatsapp"

## Cryptography Configuration
CRYPT_PRIVATE_KEY_FILE: "./config/keys/private.key"
CRYPT_PUBLIC_KEY_FILE: "./config/keys/public.key"

## Basic Auth Configuration
AUTH_BASIC_PASSWORD: "83e4060e-78e1-4fe5-9977-aeeccd46a2b8"

## WhatsApp Configuration
WHATSAPP_CLIENT_VERSION_MAJOR: 2
WHATSAPP_CLIENT_VERSION_MINOR: 2114
WHATSAPP_CLIENT_VERSION_BUILD: 10
